# Generated by Django 4.0.3 on 2022-04-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0002_infoappeal_answer_date_inforequest_answer_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoappeal',
            name='original_request',
        ),
        migrations.AddField(
            model_name='inforequest',
            name='appeal',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='request_management.infoappeal'),
        ),
    ]
