# Generated by Django 4.0.3 on 2022-04-14 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_demanda', models.CharField(max_length=255)),
                ('conteudo_demanda', models.TextField()),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_movimentacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('respondida', 'Respondida'), ('aberta-recurso', 'Recurso'), ('finalizada', 'Finalizada')], default='aberta', max_length=30)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
